/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "GPIO_Driver.h"

void USER_Delay( void );

int main(void)
{
  RCC->APB2ENR |= ( 0x1UL << 2U );	// PORTA Clock Enable
  RCC->APB2ENR |= ( 0x1UL << 4U );	// PORTC Clock Enable

  // PA5 as OUT 10 MHz

  USER_GPIO_DEFINE(PORTA, 5, OUT_10, OUT_GP_PP);
  USER_GPIO_WRITE(PORTA, 5, 0);

  // PC13 as INP pull-up

  USER_GPIO_DEFINE(PORTC, 13, INP, INP_PP);
  USER_GPIO_WRITE(PORTC, 13, 1);

  for (;;) {
    if( !USER_GPIO_READ(PORTC, 13) )
    {
	USER_Delay( );

	if( !USER_GPIO_READ(PORTC, 13) )
	{
	    USER_GPIO_TOGGLE(PORTA, 5);
	    while( !USER_GPIO_READ(PORTC, 13) ){ }
	    USER_Delay( );
	}
    }
  }
}

void USER_Delay( void ){
  __asm("LDR r0, =250000");
  __asm("again: sub r0, r0, #1");
  __asm("CMP r0, #0");
  __asm("BNE again");
}
